
MIGRATIONS_DIR=db/migrations
# DB_URL=root:admin12@tcp(127.0.0.1:3306)/airbnb_auth_dev
DB_URL=root:hccAARxpRxTLfiftXOsiEERUrFZrPcuC@tcp(mysql.railway.internal:3306)/airbnb_auth_dev

migrate-create:
	goose -dir $(MIGRATIONS_DIR) create $(name) sql
migrate-up:
	goose -dir $(MIGRATIONS_DIR) mysql "$(DB_URL)" up
migrate-down:
	goose -dir $(MIGRATIONS_DIR) mysql "$(DB_URL)" down				
# Rollback all migrations and reset database # gmake migrate-reset
migrate-reset:
	goose -dir $(MIGRATIONS_DIR) mysql "$(DB_URL)" reset
# Show current migration status # gmake migrate-status
migrate-status:
	goose -dir $(MIGRATIONS_DIR) mysql "$(DB_URL)" status

# Redo last migration (Down then Up) # gmake migrate-redo
migrate-redo:
	goose -dir $(MIGRATIONS_DIR) mysql "$(DB_URL)" redo

# Run specific migration version # gmake migrate-version version=20200101120000
migrate-to:
	goose -dir $(MIGRATIONS_DIR) mysql "$(DB_URL)" up-to $(version)

# Rollback to a specific migration version # gmake migrate-down-to version=20200101120000
migrate-down-to:
	goose -dir $(MIGRATIONS_DIR) mysql "$(DB_URL)" down-to $(version)

# Force a specific migration version # gmake migrate-force version=20200101120000
migrate-force:
	goose -dir $(MIGRATIONS_DIR) mysql "$(DB_URL)" force $(version)

# Print Goose help # gmake migrate-help
migrate-help:
	goose -h